### Data Sources

### Step 1: Import Libraries

In [2]:
import sys
sys.path.append('/Users/teslim/TeslimWorkSpace/MainClass/1-Modules-Python')

from onedrive_loader import load_csv, load_file

In [5]:
import requests
from onedrive_loader import _get_token, USER_EMAIL

# List what's directly inside TeslimDataLakes
url = f"https://graph.microsoft.com/v1.0/users/{USER_EMAIL}/drive/root:/TeslimDataLakes:/children"
response = requests.get(url, headers={"Authorization": f"Bearer {_get_token()}"})
print(response.json())

{'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)', 'value': [{'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-05-03T00:36:55Z', 'eTag': '"{C54A16EE-43F9-4561-8480-FFE8CE7C45C8},1"', 'id': '01NWPYULHOCZFML6KDMFCYJAH75DHHYROI', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-05-03T00:36:55Z', 'name': 'financial_transactions_dataset_analytics_kaggle', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/financial_transactions_dataset_analytics_kaggle', 'cTag': '"c:{C54A16EE-43F9-4561-8480-FFE8CE7C45C8},0"', 'fileSystemInfo': {'createdDateTime': '2026-05-03T00:36:55Z', 'lastModifiedDateTime': '2026-05-03T00:36:55Z'}, 'folder': {'childCount': 4}, 'isAuthoritative': False, 'size': 159762495}, {'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-05-03T00:38:33Z', 'eTag': '"{83CD4B24-9487-4E74-A3B6-6BD31418D051},2"', 'id': '01NWPYULBEJPGYHB4UORHKHNTL2MKBRUCR', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-05-03T00:50:41Z', 'name': 'nhs-waiting-list-analytics_data', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/nhs-waiting-list-analytics_data', 'cTag': '"c:{83CD4B24-9487-4E74-A3B6-6BD31418D051},0"', 'fileSystemInfo': {'createdDateTime': '2026-05-03T00:38:33Z', 'lastModifiedDateTime': '2026-05-03T00:50:41Z'}, 'folder': {'childCount': 3}, 'isAuthoritative': False, 'size': 1900447226}, {'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-05-13T23:22:48Z', 'eTag': '"{3B15D0CC-ACE6-4D63-AD00-0D485D75A730},2"', 'id': '01NWPYULGM2AKTXZVMMNG22AANJBOXLJZQ', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-05-13T23:22:48Z', 'name': 'Portfolio-22-Financial-Performance-Analytics-Model', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/Portfolio-22-Financial-Performance-Analytics-Model', 'cTag': '"c:{3B15D0CC-ACE6-4D63-AD00-0D485D75A730},0"', 'fileSystemInfo': {'createdDateTime': '2026-05-13T23:22:48Z', 'lastModifiedDateTime': '2026-05-13T23:22:48Z'}, 'folder': {'childCount': 1, 'decorator': {'iconColor': 'darkGreen'}}, 'isAuthoritative': False, 'size': 83418}, {'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-05-03T00:36:55Z', 'eTag': '"{9A8C8464-7B2A-4BBF-9FC5-61C3B00B094F},1"', 'id': '01NWPYULDEQSGJUKT3X5FZ7RLBYOYAWCKP', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-05-03T00:36:55Z', 'name': 'region_electric_hourly_time_series', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/region_electric_hourly_time_series', 'cTag': '"c:{9A8C8464-7B2A-4BBF-9FC5-61C3B00B094F},0"', 'fileSystemInfo': {'createdDateTime': '2026-05-03T00:36:55Z', 'lastModifiedDateTime': '2026-05-03T00:36:55Z'}, 'folder': {'childCount': 17}, 'isAuthoritative': False, 'size': 46597766}, {'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-04-01T23:04:10Z', 'eTag': '"{AC8EC7B2-E26F-454D-97A4-933C3413B18A},4"', 'id': '01NWPYULFSY6HKY37CJVCZPJETHQ2BHMMK', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-04-01T23:15:15Z', 'name': 'SalesForecast', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/SalesForecast', 'cTag': '"c:{AC8EC7B2-E26F-454D-97A4-933C3413B18A},0"', 'fileSystemInfo': {'createdDateTime': '2026-04-01T23:04:10Z', 'lastModifiedDateTime': '2026-04-01T23:15:15Z'}, 'folder': {'childCount': 6, 'decorator': {'iconColor': 'lightTeal'}}, 'isAuthoritative': False, 'size': 10933471}, {'createdBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'createdDateTime': '2026-05-03T00:36:55Z', 'eTag': '"{E8DD8C80-5AA8-42E8-AA16-E85BF4543916},1"', 'id': '01NWPYULEARTO6RKC25BBKUFXILP2FIOIW', 'lastModifiedBy': {'user': {'email': 'info@adeyanjuteslim.co.uk', 'id': '481f31a2-aaed-49e1-a8df-26bc73bfca40', 'displayName': 'Teslim Uthman Adeyanju'}}, 'lastModifiedDateTime': '2026-05-03T00:36:55Z', 'name': 'sundry_data_sources', 'parentReference': {'driveType': 'business', 'driveId': 'b!llVkUYedrk6m1kJ0Npolnqs0TICtI1tIhe6antm0iFMus0614tDmQ545zkHBly9Z', 'id': '01NWPYULELJ7GOC2IK4FH2ONF6TFCEF64O', 'name': 'TeslimDataLakes', 'path': '/drive/root:/TeslimDataLakes', 'siteId': '51645596-9d87-4eae-a6d6-4274369a259e'}, 'webUrl': 'https://teslimuthmanadeyanju-my.sharepoint.com/personal/info_adeyanjuteslim_co_uk/Documents/TeslimDataLakes/sundry_data_sources', 'cTag': '"c:{E8DD8C80-5AA8-42E8-AA16-E85BF4543916},0"', 'fileSystemInfo': {'createdDateTime': '2026-05-03T00:36:55Z', 'lastModifiedDateTime': '2026-05-03T00:36:55Z'}, 'folder': {'childCount': 15}, 'isAuthoritative': False, 'size': 18057151}]}

In [6]:
# First list files to see exact filenames
files = list_files("financial_transactions_dataset_analytics_kaggle")
print(files)

# Then load
df = load_csv("financial_transactions_dataset_analytics_kaggle", "transactions.csv")

['cards_data.csv', 'mcc_codes.json', 'train_fraud_labels.json', 'users_data.csv']

HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/users/info@adeyanjuteslim.co.uk/drive/root:/TeslimDataLakes/financial_transactions_dataset_analytics_kaggle/transactions.csv:/content

In [3]:
from onedrive_loader import load_csv, load_excel, load_json, load_file, list_files

# Load a CSV
df = load_csv("FinancialData", "transactions.csv")

# Load Excel (first sheet by default)
df = load_excel("FinancialData", "report.xlsx")

# Load Excel — specific sheet
df = load_excel("FinancialData", "report.xlsx", sheet_name="Summary")

# Auto-detect file type (recommended)
df = load_file("FinancialData", "data.parquet")

# List what's in a folder
files = list_files("FinancialData")

HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/users/info@adeyanjuteslim.co.uk/drive/root:/TeslimDataLakes/FinancialData/transactions.csv:/content

pip install fda-toolkit

In [22]:
import sys
import pandas as pd
import numpy as np
import fda_toolkit as ftk

In [23]:
# Set multiple display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

___

In [24]:
df = pd.read_excel('data.xlsx', sheet_name='2025')
df

,Estimates of End-of-Month Retail Inventories and Inventories/Sales Ratios by Kind of Business: 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,"[Estimates are shown in millions of dollars and are based on data from the Monthly Retail Trade Survey, Annual Retail Trade Survey, and administrative records]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NAICS Code,Kind of Business,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Jan. 2025,Feb. 2025,Mar. 2025,Apr. 2025,May 2025,Jun. 2025,Jul. 2025(p)
4,NaN,NOT ADJUSTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,"Retail Inventories, total",795462,801781,801706,802082,796569,799444,795698
6,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,534606,540605,546755,547921,543524,542567,542265
7,441,Motor vehicle and parts dealers,260856,261176,254951,254161,253045,256877,253433
8,"442,443","Furniture, home furn, electronics, and appliance stores",28192,28432,28442,28806,29315,29676,29702
9,444,"Building materials, garden equip. and supplies dealers",81979,84902,87050,87748,85495,83438,82500
10,445,Food and beverage stores,61608,61285,61458,62042,62230,62093,62144
11,448,Clothing and clothing access. stores,55466,57309,57983,58110,57153,57357,57654
12,452,General merchandise stores,95089,95910,97161,97539,95576,94622,95617
13,4522,Department stores,8014,8477,8728,8651,8380,8189,8027
14,NaN,ADJUSTED(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,"Retail Inventories, total",807460,806604,804552,804501,806437,807816,809789
16,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,547532,548311,550054,551743,552122,551282,552038
17,441,Motor vehicle and parts dealers,259928,258293,254498,252758,254315,256534,257751
18,"442,443","Furniture, home furn, electronics, and appliance stores",29094,29072,29171,29424,29761,29825,29942
19,444,"Building materials, garden equip. and supplies dealers",83059,82993,82826,83411,83410,83689,84012
20,445,Food and beverage stores,61992,62204,62041,62673,62718,62728,63123
21,448,Clothing and clothing access. stores,58570,58419,58333,58343,58141,58349,58236
22,452,General merchandise stores,98855,98674,99496,99061,98956,98271,97973
23,4522,Department stores,8994,8999,8888,8819,8784,8796,8687
24,NaN,"INVENTORIES/SALES, RATIOS NOT ADJUSTED",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,"Retail Trade, total",1.4,1.47,1.28,1.29,1.23,1.3,1.24
26,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,1.2,1.28,1.16,1.15,1.08,1.13,1.09
27,441,Motor vehicle and parts dealers,2.13,2.14,1.67,1.72,1.75,1.9,1.75
28,"442,443","Furniture, home furn, electronics, and appliance stores",1.61,1.67,1.52,1.6,1.53,1.63,1.53
29,444,"Building materials, garden equip. and supplies dealers",2.49,2.69,2.19,1.95,1.83,1.9,1.91
30,445,Food and beverage stores,0.74,0.8,0.74,0.75,0.71,0.75,0.71
31,448,Clothing and clothing access. stores,2.85,2.77,2.32,2.35,2.05,2.3,2.16
32,452,General merchandise stores,1.37,1.44,1.29,1.32,1.2,1.25,1.25
33,4522,Department stores,3.6,3.36,2.98,2.88,2.51,2.82,2.77
34,NaN,"INVENTORIES/SALES, RATIOS ADJUSTED(1)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,"Retail Trade, total",1.31,1.31,1.29,1.29,1.3,1.29,1.29
36,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,1.14,1.14,1.14,1.14,1.14,1.13,1.13
37,441,Motor vehicle and parts dealers,1.91,1.92,1.8,1.8,1.88,1.88,1.85
38,"442,443","Furniture, home furn, electronics, and appliance stores",1.54,1.53,1.52,1.53,1.56,1.56,1.54
39,444,"Building materials, garden equip. and supplies dealers",2.08,2.08,2.04,2.04,2.1,2.08,2.1
40,445,Food and beverage stores,0.74,0.74,0.74,0.74,0.75,0.74,0.74
41,448,Clothing and clothing access. stores,2.28,2.28,2.25,2.24,2.22,2.2,2.16
42,452,General merchandise stores,1.28,1.29,1.3,1.29,1.29,1.28,1.28
43,4522,Department stores,2.75,2.74,2.72,2.73,2.72,2.75,2.68
44,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,(p) Preliminary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"(1) Estimates are adjusted for seasonal variation and trading-day differences, and in the case of sales for holiday effects. Estimates are not adjusted for price changes.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,"Note: Estimates exclude food services. Inventory estimates include data for auxiliary establishments; for example, warehouses servicing retail stores.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,"Estimates include data only for businesses with paid employees. Prior to the benchmark report released in April 2025, the Monthly Retail Trade Survey estimates included nonemployers.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,"For surveyed Retail companies, approximately 44.6% provided data for this reporting period, resulting in a total quantity response rate of 57.4% for inventories.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,"Information on sample design, estimation procedures, and measures of sampling variability can be found on the Internet at http://www.census.gov/retail/mrts/how_surveys_are_collected.html",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,"Source: The Census Bureau has reviewed this data product to ensure appropriate access, use, and disclosure avoidance protection of the confidential source data",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,"(Project No. P-7504206, Disclosure Review Board (DRB) approval number: CBDRB-FY25-0002).",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
display(ftk.info())

In [26]:
from fda_toolkit.core import columns, duplicates, missing, outliers, text, types

In [28]:
df = columns.clean_column_headers(df)
df

,estimates_of_endofmonth_retail_inventories_and_inventoriessales_ratios_by_kind_of_business_2025,unnamed_1,unnamed_2,unnamed_3,unnamed_4,unnamed_5,unnamed_6,unnamed_7,unnamed_8
0,"[Estimates are shown in millions of dollars and are based on data from the Monthly Retail Trade Survey, Annual Retail Trade Survey, and administrative records]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NAICS Code,Kind of Business,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Jan. 2025,Feb. 2025,Mar. 2025,Apr. 2025,May 2025,Jun. 2025,Jul. 2025(p)
4,NaN,NOT ADJUSTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,"Retail Inventories, total",795462,801781,801706,802082,796569,799444,795698
6,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,534606,540605,546755,547921,543524,542567,542265
7,441,Motor vehicle and parts dealers,260856,261176,254951,254161,253045,256877,253433
8,"442,443","Furniture, home furn, electronics, and appliance stores",28192,28432,28442,28806,29315,29676,29702
9,444,"Building materials, garden equip. and supplies dealers",81979,84902,87050,87748,85495,83438,82500
10,445,Food and beverage stores,61608,61285,61458,62042,62230,62093,62144
11,448,Clothing and clothing access. stores,55466,57309,57983,58110,57153,57357,57654
12,452,General merchandise stores,95089,95910,97161,97539,95576,94622,95617
13,4522,Department stores,8014,8477,8728,8651,8380,8189,8027
14,NaN,ADJUSTED(1),NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,"Retail Inventories, total",807460,806604,804552,804501,806437,807816,809789
16,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,547532,548311,550054,551743,552122,551282,552038
17,441,Motor vehicle and parts dealers,259928,258293,254498,252758,254315,256534,257751
18,"442,443","Furniture, home furn, electronics, and appliance stores",29094,29072,29171,29424,29761,29825,29942
19,444,"Building materials, garden equip. and supplies dealers",83059,82993,82826,83411,83410,83689,84012
20,445,Food and beverage stores,61992,62204,62041,62673,62718,62728,63123
21,448,Clothing and clothing access. stores,58570,58419,58333,58343,58141,58349,58236
22,452,General merchandise stores,98855,98674,99496,99061,98956,98271,97973
23,4522,Department stores,8994,8999,8888,8819,8784,8796,8687
24,NaN,"INVENTORIES/SALES, RATIOS NOT ADJUSTED",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,"Retail Trade, total",1.4,1.47,1.28,1.29,1.23,1.3,1.24
26,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,1.2,1.28,1.16,1.15,1.08,1.13,1.09
27,441,Motor vehicle and parts dealers,2.13,2.14,1.67,1.72,1.75,1.9,1.75
28,"442,443","Furniture, home furn, electronics, and appliance stores",1.61,1.67,1.52,1.6,1.53,1.63,1.53
29,444,"Building materials, garden equip. and supplies dealers",2.49,2.69,2.19,1.95,1.83,1.9,1.91
30,445,Food and beverage stores,0.74,0.8,0.74,0.75,0.71,0.75,0.71
31,448,Clothing and clothing access. stores,2.85,2.77,2.32,2.35,2.05,2.3,2.16
32,452,General merchandise stores,1.37,1.44,1.29,1.32,1.2,1.25,1.25
33,4522,Department stores,3.6,3.36,2.98,2.88,2.51,2.82,2.77
34,NaN,"INVENTORIES/SALES, RATIOS ADJUSTED(1)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,"Retail Trade, total",1.31,1.31,1.29,1.29,1.3,1.29,1.29
36,"44,45 excl. 441",Total excluding motor vehicle and parts dealers,1.14,1.14,1.14,1.14,1.14,1.13,1.13
37,441,Motor vehicle and parts dealers,1.91,1.92,1.8,1.8,1.88,1.88,1.85
38,"442,443","Furniture, home furn, electronics, and appliance stores",1.54,1.53,1.52,1.53,1.56,1.56,1.54
39,444,"Building materials, garden equip. and supplies dealers",2.08,2.08,2.04,2.04,2.1,2.08,2.1
40,445,Food and beverage stores,0.74,0.74,0.74,0.74,0.75,0.74,0.74
41,448,Clothing and clothing access. stores,2.28,2.28,2.25,2.24,2.22,2.2,2.16
42,452,General merchandise stores,1.28,1.29,1.3,1.29,1.29,1.28,1.28
43,4522,Department stores,2.75,2.74,2.72,2.73,2.72,2.75,2.68
44,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,(p) Preliminary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"(1) Estimates are adjusted for seasonal variation and trading-day differences, and in the case of sales for holiday effects. Estimates are not adjusted for price changes.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,"Note: Estimates exclude food services. Inventory estimates include data for auxiliary establishments; for example, warehouses servicing retail stores.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,"Estimates include data only for businesses with paid employees. Prior to the benchmark report released in April 2025, the Monthly Retail Trade Survey estimates included nonemployers.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,"For surveyed Retail companies, approximately 44.6% provided data for this reporting period, resulting in a total quantity response rate of 57.4% for inventories.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,"Information on sample design, estimation procedures, and measures of sampling variability can be found on the Internet at http://www.census.gov/retail/mrts/how_surveys_are_collected.html",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,"Source: The Census Bureau has reviewed this data product to ensure appropriate access, use, and disclosure avoidance protection of the confidential source data",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,"(Project No. P-7504206, Disclosure Review Board (DRB) approval number: CBDRB-FY25-0002).",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN