# Series df[series]

In [24]:

import pandas as pd
import seaborn as sns

# Load Titanic dataset
df = sns.load_dataset('titanic')

In [25]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## 2. Pandas Series: Access & Selection

### 1. Label-Based & Positional Access

### df['age'].at[label]

In [26]:
df['age'].at[0]

22.0

In [27]:
df['sex'].at[2]

'female'

In [28]:
df['age'].at[5]

nan

### df['age'].iat[position]

In [29]:
df['age'].iat[10]

4.0

In [30]:
df['fare'].iat[13]

31.275

### df['age'].loc[label]

In [31]:
df['age'].loc[12]

20.0

In [32]:
df['pclass'].loc[[2,4,5]] + df['age'].loc[[2,4,5]]

2    29.0
4    38.0
5     NaN
dtype: float64

In [33]:
df.loc[0, 'age']

22.0

In [34]:
print(df.loc[[0,2,15,6,10,11], 'age'])

0     22.0
2     26.0
15    55.0
6     54.0
10     4.0
11    58.0
Name: age, dtype: float64

In [35]:
df.loc[0, ['age', 'fare', 'sex']]

age     22.0
fare    7.25
sex     male
Name: 0, dtype: object

In [36]:
df.loc[[1, 3, 5, 10], ['sex', 'age', 'fare']]

       sex   age     fare
1   female  38.0  71.2833
3   female  35.0  53.1000
5     male   NaN   8.4583
10  female   4.0  16.7000

In [37]:
df.loc[0:4, 'age':'fare']

    age  sibsp  parch     fare
0  22.0      1      0   7.2500
1  38.0      1      0  71.2833
2  26.0      0      0   7.9250
3  35.0      1      0  53.1000
4  35.0      0      0   8.0500

In [38]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [41]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [44]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [48]:
# Single Row, Single Column : df.loc[row_label, column_label]
df.loc[10, 'age']

4.0

In [47]:
# Multiple Rows, Single Column: df.loc[[row_label1, row_label2], column_label]
df.loc[[10, 20, 30], 'age']

10     4.0
20    35.0
30    40.0
Name: age, dtype: float64

### 2. Value Retrieval & Conversion

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df['age'].get(0)

np.float64(22.0)

In [ ]:
df['fare'].get(2)

np.float64(7.925)

In [ ]:
df['age'].iloc[[0]].item()

22.0

In [ ]:
df['fare'].array[:10]

<NumpyExtensionArray>
[   np.float64(7.25), np.float64(71.2833),   np.float64(7.925),
    np.float64(53.1),    np.float64(8.05),  np.float64(8.4583),
 np.float64(51.8625),  np.float64(21.075), np.float64(11.1333),
 np.float64(30.0708)]
Length: 10, dtype: float64

In [ ]:
df['age'].items

<bound method Series.items of 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64>

In [ ]:
for i, val in df['age'].items():
    print(i, val)
    if i >= 4:
        break

0 22.0
1 38.0
2 26.0
3 35.0
4 35.0

In [ ]:
df['age'].iter()

AttributeError: 'Series' object has no attribute 'iter'

### 3. Data Removal & Iteration

### 4. Advanced Selection

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
df['age'].add(100)

0      122.0
1      138.0
2      126.0
3      135.0
4      135.0
       ...
886    127.0
887    119.0
888      NaN
889    126.0
890    132.0
Name: age, Length: 891, dtype: float64

In [ ]:
df['age'].div(5)

0      4.4
1      7.6
2      5.2
3      7.0
4      7.0
      ...
886    5.4
887    3.8
888    NaN
889    5.2
890    6.4
Name: age, Length: 891, dtype: float64

In [ ]:
df['age'].truediv(5)

0      4.4
1      7.6
2      5.2
3      7.0
4      7.0
      ...
886    5.4
887    3.8
888    NaN
889    5.2
890    6.4
Name: age, Length: 891, dtype: float64

In [ ]:
df['age'].radd(100)

0      122.0
1      138.0
2      126.0
3      135.0
4      135.0
       ...
886    127.0
887    119.0
888      NaN
889    126.0
890    132.0
Name: age, Length: 891, dtype: float64

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
print(df['age'].sub(10))
print(df['age'].rsub(10))

0      12.0
1      28.0
2      16.0
3      25.0
4      25.0
       ...
886    17.0
887     9.0
888     NaN
889    16.0
890    22.0
Name: age, Length: 891, dtype: float64
0     -12.0
1     -28.0
2     -16.0
3     -25.0
4     -25.0
       ...
886   -17.0
887    -9.0
888     NaN
889   -16.0
890   -22.0
Name: age, Length: 891, dtype: float64

In [ ]:
a = df[df['age'].eq(12)]
a

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
125,1,3,male,12.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False