# Series df[series]

In [48]:
import pandas as pd
import numpy as np
from onedrive_loader import files, load

In [17]:
files()

['financial_transactions_dataset_analytics_kaggle',
 'nhs-waiting-list-analytics_data',
 'portfolio-01-nhs-financial-analytics',
 'Portfolio-22-Financial-Performance-Analytics-Model',
 'region_electric_hourly_time_series',
 'SalesForecast',
 'sundry_data_sources']

In [18]:
dataset = 'sundry_data_sources'
files(dataset)

['22025_qs_world_university_rankings.csv',
 'adidas_us_sales_datasets.xlsx',
 'apple_amazon_google_microsoft_daily_stock_returns_10years.xlsx',
 'country_economy_indicator_1950_2022.xlsx',
 'country_gdp_per_capital_1952_2007.xlsx',
 'end_of_month_retail_inventories_and_inventories1992_2024.xlsx',
 'financial_sample_data.xlsx',
 'job_roles_opening_analyst.xlsx',
 'monthly_retail_and_food_services_sales_by_kind_of_business1992_2025.xlsx',
 'motor_fuel_efficiency_mpg.xlsx',
 'pivot_data_example.xlsx',
 'retail_transaction_loyalty_discount_report.xlsx',
 'skilled_worker_employer_sponsorship_list.xlsx',
 'time_series_data.xlsx',
 'uk_constituency_election_result_2019_and_2024.xlsx',
 'uk_election_result_poll.xlsx',
 'uk_house_of_commons_general_election_2024_results_by_constituency.xlsx',
 'uk_smoking_data.csv']

In [19]:
df = load(dataset,'financial_sample_data.xlsx')
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year,Unnamed: 16,Unnamed: 17
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014,NaN,NaN
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014,NaN,NaN
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014,NaN,NaN
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014,NaN,NaN
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014,NaN,NaN
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014,NaN,NaN
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014,NaN,NaN
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014,NaN,NaN
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014,NaN,NaN

____

In [20]:
df.columns.to_list()

['Segment',
 'Country',
 'Product',
 'Discount Band',
 'Units Sold',
 'Manufacturing Price',
 'Sale Price',
 'Gross Sales',
 'Discounts',
 ' Sales',
 'COGS',
 'Profit',
 'Date',
 'Month Number',
 'Month Name',
 'Year',
 'Unnamed: 16',
 'Unnamed: 17']

In [33]:
def clean_columns_header(df):
    df.columns = df.columns.str.strip().str.lower()
    df.columns = df.columns.str.replace(' ', '_')
    return df

In [34]:
df = clean_columns_header(df)
df.columns.to_list()

['segment',
 'country',
 'product',
 'discount_band',
 'units_sold',
 'manufacturing_price',
 'sale_price',
 'gross_sales',
 'discounts',
 'sales',
 'cogs',
 'profit',
 'date',
 'month_number',
 'month_name',
 'year',
 'unnamed:_16',
 'unnamed:_17']

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   segment              700 non-null    str
 1   country              700 non-null    str
 2   product              700 non-null    str
 3   discount_band        647 non-null    str
 4   units_sold           700 non-null    float64
 5   manufacturing_price  700 non-null    int64
 6   sale_price           700 non-null    int64
 7   gross_sales          700 non-null    float64
 8   discounts            700 non-null    float64
 9   sales                700 non-null    float64
 10  cogs                 700 non-null    float64
 11  profit               700 non-null    float64
 12  date                 700 non-null    datetime64[us]
 13  month_number         700 non-null    int64
 14  month_name           700 non-null    str
 15  year                 700 non-null    int64
 16  unnamed:_16          0 non-null      float64
 17  unnamed:_17          0 non-null      float64
dtypes: datetime64[us](1), float64(8), int64(4), str(5)
memory usage: 124.3 KB

In [36]:
df

,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year,unnamed:_16,unnamed:_17
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014,NaN,NaN
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014,NaN,NaN
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.00,32670.00,21780.0,10890.00,2014-06-01,6,June,2014,NaN,NaN
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,2014-06-01,6,June,2014,NaN,NaN
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.00,37050.00,24700.0,12350.00,2014-06-01,6,June,2014,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,2014-03-01,3,March,2014,NaN,NaN
696,Small Business,Mexico,Amarilla,High,546.0,260,300,163800.0,24570.00,139230.00,136500.0,2730.00,2014-10-01,10,October,2014,NaN,NaN
697,Government,Mexico,Montana,High,1368.0,5,7,9576.0,1436.40,8139.60,6840.0,1299.60,2014-02-01,2,February,2014,NaN,NaN
698,Government,Canada,Paseo,High,723.0,10,7,5061.0,759.15,4301.85,3615.0,686.85,2014-04-01,4,April,2014,NaN,NaN
699,Channel Partners,United States of America,VTT,High,1806.0,250,12,21672.0,3250.80,18421.20,5418.0,13003.20,2014-05-01,5,May,2014,NaN,NaN

In [37]:
df['product'].index

RangeIndex(start=0, stop=700, step=1)

In [38]:
df['country'].index

RangeIndex(start=0, stop=700, step=1)

In [39]:
df['country'].dtypes

In [40]:
df['product'].size

700

In [41]:
df['country'].values[:5].tolist()

['Canada', 'Germany', 'France', 'Germany', 'Mexico']

In [42]:
df['gross_sales'].values[:10].tolist()

[32370.0,
 26420.0,
 32670.0,
 13320.0,
 37050.0,
 529550.0,
 13815.0,
 30216.0,
 37980.0,
 18540.0]

In [44]:
df['discount_band'].hasnans

True

In [51]:
df['discount_band'].isnull().sum()

np.int64(53)

In [63]:
df['discount_band'].attrs = {'description': 'Discount band for the product', 'source': 'Financial Sample Data', 'last_updated': '2024-06-01'}

In [62]:
print(df['discount_band'].attrs)

{}