### Function wthout parameters

In [2]:
#  define the function 

def welcome_function():
    print("Welcome to the Python programming world!")
    print("+" *30)
    print("This function demonstrates how to define and call a function in Python.")

In [3]:
welcome_function()

Welcome to the Python programming world!
++++++++++++++++++++++++++++++
This function demonstrates how to define and call a function in Python.

## Function With Parameters

In [4]:
def student_info(name, age, grade):
    print(f"Student Name: {name}")
    print(f"Age: {age}")
    print(f"Grade: {grade}")

In [4]:
student_info("Alice", 14, "8th Grade")

Student Name: Alice
Age: 14
Grade: 8th Grade

###  Function with return

In [5]:
def  work_hours(hourly_rate, hours_worked):
    total_pay = hourly_rate * hours_worked
    average = total_pay / hours_worked
    number_days = hours_worked / 8
    return total_pay

In [6]:
work_hours(20, 160)

3200

In [3]:
def calculate_average(numbers):
    # Early return for empty list
    if len(numbers) == 0:
        return 0

    # Early return for single item
    if len(numbers) == 1:
        return numbers[0]

    # Normal calculation (final return at end)
    return sum(numbers) / len(numbers)

In [5]:
calculate_average([10, 20, 30, 40, 50, 0])

25.0

In [7]:
def student_state(name, age):
    if age < 18:
        return f"{name} is a minor."
    if age >= 18:
        return f"{name} is an adult."
    if age < 0:
        return "Age cannot be negative."
    else:
        return f"{name} is an adult."

In [8]:
student_state("Alice", 14)
student_state("Bob", 20)
student_state("Charlie", -5)

'Charlie is a minor.'

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [14, 20, -5]
})

In [4]:
df

      Name  Age
0    Alice   14
1      Bob   20
2  Charlie   -5

In [9]:
def process_data(df):
    # Step 1: Clean data
    cleaned = [x.strip() for x in df['Name']]

    # Step 2: Filter data
    filtered = [x for x in cleaned if x]

    # Step 3: Transform data
    transformed = [x.upper() for x in filtered]

    # Step 4: Return final result (AT THE END)
    return transformed

In [10]:
process_data(df)

['ALICE', 'BOB', 'CHARLIE']

In [ ]:
def top_sales§

In [1]:
student ={}

def add_student(name, age, grade):
    student['Name'] = name
    student['Age'] = age
    student['Grade'] = grade
    return student

In [2]:
add_student("Alice", 14, "8th Grade")

{'Name': 'Alice', 'Age': 14, 'Grade': '8th Grade'}

In [4]:

# Global variable
x = 100

def function1():
    print("Value in 1st function:", x)

def function2():
    global x  # Tells Python to use the global variable x
    x = 5550
    print("Value in 2nd function:", x)

def function3():
    print("Value in 3rd function:", x)

function1()
function2()
function3()

Value in 1st function: 100
Value in 2nd function: 5550
Value in 3rd function: 5550

In [9]:

def outer_func():
    x = 777

    def inner_func():
        nonlocal x  # Tells Python to use the nearest enclosing variable x
        x = 700  # This creates a new local variable instead of modifying outer x
        print("Value of x inside inner function is:", x)

    inner_func()
    print("Value of x inside outer function is:", x)

# Call the outer function
outer_func()

Value of x inside inner function is: 700
Value of x inside outer function is: 700

In [1]:
def send_email(to, subject, body, sender = 'info@admin.com', cc = None, bcc = None):
    print(f"Sending email to: {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")
    print(f"Sender: {sender}")
    if cc:
        print(f"CC: {cc}")
    if bcc:
        print(f"BCC: {bcc}")

In [2]:
send_email("recipient@example.com", "Meeting Reminder", "Don't forget about the meeting at 10 AM tomorrow.")

Sending email to: recipient@example.com
Subject: Meeting Reminder
Body: Don't forget about the meeting at 10 AM tomorrow.
Sender: info@admin.com

In [16]:
def student(*args):
    total = 0
    for i in args:
        total = total + 100
    return total

In [15]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [14, 20, -5]
})

df

      Name  Age
0    Alice   14
1      Bob   20
2  Charlie   -5

In [9]:
df['Age']

0    14
1    20
2    -5
Name: Age, dtype: int64

In [8]:
student(df['Age'])

0    14
1    20
2    -5
Name: Age, dtype: int64

In [17]:
for i in df['Age']:
    sum = student(i)
    print(sum)

100
100
100

In [20]:
def work_hours(*data):
    total = 0
    for i in data:
        total = total + i
    return total

In [21]:
work_hours(8, 8, 8, 8, 8, 8, 8, 8)

64

In [1]:
def percentages(**data):
    for key, value in data.items():
        print(f"{key}: {value}%")
        
        
percentages(Math=90, Science=85, English=92)

Math: 90%
Science: 85%
English: 92%

In [4]:
lambda data: {key: value for key, value in data.items()}
print(data)

{'Math': 90, 'Science': 85, 'English': 92}

In [5]:
data = {'Math': 90, 'Science': 85, 'English': 92}

In [ ]:
def calculate_average(numbers):
    # Early return for empty list
    if len(numbers) == 0:
        return 0

    # Early return for single item
    if len(numbers) == 1:
        return numbers[0]

    # Normal calculation (final return at end)
    return sum(numbers) / len(numbers)

In [13]:
lambda_function = lambda x: x * 2

In [14]:
lambda_function.__doc__

In [16]:
dir(lambda)

SyntaxError: invalid syntax (3093142102.py, line 1)

In [17]:
lambda a, b: a + b
return a, b

SyntaxError: 'return' outside function (3802298969.py, line 2)

In [20]:
count = lambda a, b, c: a + b + c
print(count(11, 2, 3))  # Output: 6

16

In [ ]:
def send_email(to, subject, body, sender = 'info@admin.com', cc = None, bcc = None):
    print(f"Sending email to: {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")
    print(f"Sender: {sender}")
    if cc:
        print(f"CC: {cc}")
    if bcc:
        print(f"BCC: {bcc}")

## Lambda vs Regular Functions - send_email Example

Lambda functions are designed for **simple, single-expression operations**. The `send_email` function has multiple statements and conditional logic, making it unsuitable for lambda.

In [ ]:
# ❌ BAD: Forcing send_email into a lambda (Don't do this!)
# This is technically possible but violates Python best practices

send_email_lambda = lambda to, subject, body, sender='info@admin.com', cc=None, bcc=None: (
    print(f"Sending email to: {to}"),
    print(f"Subject: {subject}"),
    print(f"Body: {body}"),
    print(f"Sender: {sender}"),
    print(f"CC: {cc}") if cc else None,
    print(f"BCC: {bcc}") if bcc else None
)

# This works but is hard to read and maintain
send_email_lambda("test@example.com", "Test", "This is a test")

### Why the lambda version is BAD:
1. **Hard to read** - Multiple statements crammed into one line
2. **Hard to debug** - No clear separation of logic
3. **No docstring** - Can't document what it does
4. **Returns a tuple** - The lambda returns (None, None, None...) which is confusing
5. **Against PEP 8** - Python style guide discourages complex lambdas

### ✅ Good Uses of Lambda Functions

In [ ]:
# ✅ GOOD: Simple calculations
multiply = lambda x, y: x * y
print(multiply(5, 3))  # Output: 15

# ✅ GOOD: Simple string operations
uppercase = lambda text: text.upper()
print(uppercase("hello"))  # Output: HELLO

# ✅ GOOD: Simple formatting
format_name = lambda first, last: f"{first} {last}".title()
print(format_name("john", "doe"))  # Output: John Doe

In [ ]:
# ✅ EXCELLENT: Lambda with map, filter, sorted
numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x ** 2, numbers))
print("Squared:", squared)

# Filter even numbers
evens = list(filter(lambda x: x % 2 == 0, numbers))
print("Evens:", evens)

# Sort students by grade
students = [
    {'name': 'Alice', 'grade': 85},
    {'name': 'Bob', 'grade': 92},
    {'name': 'Charlie', 'grade': 78}
]
sorted_students = sorted(students, key=lambda s: s['grade'], reverse=True)
print("Top student:", sorted_students[0]['name'])

### 📋 Rule of Thumb: When to use Lambda vs def

**Use regular `def` functions when:**
- ✅ Multiple statements needed
- ✅ Conditional logic (if/else with multiple actions)
- ✅ Multiple print statements
- ✅ Complex logic
- ✅ Need docstrings for documentation
- ✅ Function will be reused in multiple places

**Use lambda when:**
- ✅ Single expression only
- ✅ Simple transformation (x * 2, x.upper(), etc.)
- ✅ Inline function needed (map, filter, sorted)
- ✅ One-time use callback functions
- ✅ Fits on one readable line

In [ ]:
# CONCLUSION: For send_email, stick with regular def!
def send_email(to, subject, body, sender='info@admin.com', cc=None, bcc=None):
    """
    Send an email with optional CC and BCC.
    
    Args:
        to: Recipient email address
        subject: Email subject line
        body: Email body text
        sender: Sender email (default: info@admin.com)
        cc: Optional CC recipient
        bcc: Optional BCC recipient
    """
    print(f"Sending email to: {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")
    print(f"Sender: {sender}")
    if cc:
        print(f"CC: {cc}")
    if bcc:
        print(f"BCC: {bcc}")

# Much cleaner, more maintainable, and professional!
send_email("recipient@example.com", "Meeting Reminder", "Don't forget about the meeting at 10 AM tomorrow.")

In [22]:
full_name = lambda first, last: f"{first} {last}".upper()
full_name("john", "doe")  # Output: John Doe

'JOHN DOE'