### Function wthout parameters

In [2]:
#  define the function 

def welcome_function():
    print("Welcome to the Python programming world!")
    print("+" *30)
    print("This function demonstrates how to define and call a function in Python.")

In [3]:
welcome_function()

Welcome to the Python programming world!
++++++++++++++++++++++++++++++
This function demonstrates how to define and call a function in Python.

## Function With Parameters

In [4]:
def student_info(name, age, grade):
    print(f"Student Name: {name}")
    print(f"Age: {age}")
    print(f"Grade: {grade}")

In [4]:
student_info("Alice", 14, "8th Grade")

Student Name: Alice
Age: 14
Grade: 8th Grade

###  Function with return

In [5]:
def  work_hours(hourly_rate, hours_worked):
    total_pay = hourly_rate * hours_worked
    average = total_pay / hours_worked
    number_days = hours_worked / 8
    return total_pay

In [6]:
work_hours(20, 160)

3200

In [3]:
def calculate_average(numbers):
    # Early return for empty list
    if len(numbers) == 0:
        return 0

    # Early return for single item
    if len(numbers) == 1:
        return numbers[0]

    # Normal calculation (final return at end)
    return sum(numbers) / len(numbers)

In [5]:
calculate_average([10, 20, 30, 40, 50, 0])

25.0

In [7]:
def student_state(name, age):
    if age < 18:
        return f"{name} is a minor."
    if age >= 18:
        return f"{name} is an adult."
    if age < 0:
        return "Age cannot be negative."
    else:
        return f"{name} is an adult."

In [8]:
student_state("Alice", 14)
student_state("Bob", 20)
student_state("Charlie", -5)

'Charlie is a minor.'

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [14, 20, -5]
})

In [4]:
df

      Name  Age
0    Alice   14
1      Bob   20
2  Charlie   -5

In [9]:
def process_data(df):
    # Step 1: Clean data
    cleaned = [x.strip() for x in df['Name']]

    # Step 2: Filter data
    filtered = [x for x in cleaned if x]

    # Step 3: Transform data
    transformed = [x.upper() for x in filtered]

    # Step 4: Return final result (AT THE END)
    return transformed

In [10]:
process_data(df)

['ALICE', 'BOB', 'CHARLIE']

In [ ]:
def top_sales§

In [1]:
student ={}

def add_student(name, age, grade):
    student['Name'] = name
    student['Age'] = age
    student['Grade'] = grade
    return student

In [2]:
add_student("Alice", 14, "8th Grade")

{'Name': 'Alice', 'Age': 14, 'Grade': '8th Grade'}

In [4]:

# Global variable
x = 100

def function1():
    print("Value in 1st function:", x)

def function2():
    global x  # Tells Python to use the global variable x
    x = 5550
    print("Value in 2nd function:", x)

def function3():
    print("Value in 3rd function:", x)

function1()
function2()
function3()

Value in 1st function: 100
Value in 2nd function: 5550
Value in 3rd function: 5550

In [9]:

def outer_func():
    x = 777

    def inner_func():
        nonlocal x  # Tells Python to use the nearest enclosing variable x
        x = 700  # This creates a new local variable instead of modifying outer x
        print("Value of x inside inner function is:", x)

    inner_func()
    print("Value of x inside outer function is:", x)

# Call the outer function
outer_func()

Value of x inside inner function is: 700
Value of x inside outer function is: 700

In [1]:
def send_email(to, subject, body, sender = 'info@admin.com', cc = None, bcc = None):
    print(f"Sending email to: {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")
    print(f"Sender: {sender}")
    if cc:
        print(f"CC: {cc}")
    if bcc:
        print(f"BCC: {bcc}")

In [2]:
send_email("recipient@example.com", "Meeting Reminder", "Don't forget about the meeting at 10 AM tomorrow.")

Sending email to: recipient@example.com
Subject: Meeting Reminder
Body: Don't forget about the meeting at 10 AM tomorrow.
Sender: info@admin.com

In [16]:
def student(*args):
    total = 0
    for i in args:
        total = total + 100
    return total

In [15]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [14, 20, -5]
})

df

      Name  Age
0    Alice   14
1      Bob   20
2  Charlie   -5

In [9]:
df['Age']

0    14
1    20
2    -5
Name: Age, dtype: int64

In [8]:
student(df['Age'])

0    14
1    20
2    -5
Name: Age, dtype: int64

In [17]:
for i in df['Age']:
    sum = student(i)
    print(sum)

100
100
100

In [20]:
def work_hours(*data):
    total = 0
    for i in data:
        total = total + i
    return total

In [21]:
work_hours(8, 8, 8, 8, 8, 8, 8, 8)

64